remove memory allocation for channel ordering and limit to FF_SANE_NB…
sandflow/ffmpeg-imf pull request #54
Opened 2021-09-02 10:21 UTC by MarcAntoine-Arnaud

…_CHANNELS

2021-09-02 15:01 UTC, palemieux requested changes
Shouldn't an error message be emitted if the number of channels exceed FF_SANE_NB_CHANNELS?

2021-09-07 14:43 UTC, MarcAntoine-Arnaud commented
> Shouldn't an error message be emitted if the number of channels exceed FF_SANE_NB_CHANNELS?

I have emit an warning message:
```
av_log(mxf->fc, AV_LOG_WARNING, "MCA Audio mapping: will not reassign channel ordering, the maximum number of channels supported has been reached");
```

For me it's maybe not an error because it's not impossible to process the source.
It's more the result may not be as expected.
For me an error will requires to terminate the process.

2021-09-07 19:58 UTC, palemieux commented
> I have emit an warning message:
> 
> ```
> av_log(mxf->fc, AV_LOG_WARNING, "MCA Audio mapping: will not reassign channel ordering, the maximum number of channels supported has been reached");
> ```

@MarcAntoine-Arnaud  I do not see the warning in the code.

2021-09-07 19:59 UTC, palemieux approved these changes

2021-09-08 07:53 UTC, merged